PROCESSOR 16f877	;Procesador a utilizar
INCLUDE <p16f877.INC>

VALOR equ h'20'
VALOR1 equ h'21'
VALOR2 equ h'22'

CENT EQU h'23'
DECE EQU h'24'
UNI EQU h'25'
NUM_DECIMAL EQU h'26'


NUM_HEXA EQU h'27'
ALTO_HEXA EQU h'28'
BAJO_HEXA EQU h'29'

NUM_BINARIO EQU h'30'
CONTA_BINARIO EQU h'31'

CONTADOR EQU h'32'

ORG 0
GOTO INICIO

ORG 5		;Origen del programa



INICIO: CLRF PORTA		;SALIDA TODO EL PORTA
		CLRF PORTB		;SALIDA TODO EL PORTB
		 
		BSF STATUS, 5	;BIT 5 DE STATUS = 1
		BCF STATUS, 6	;BIT 6 DE STATUS = 0, BANCO 01
		MOVLW 0X00		;CARGA A W UN 00
		MOVWF TRISB		;TRISB = 00000000
		
		MOVLW 0X07		;CARGA A W UN 07
		MOVWF ADCON1	;CONFIGURACION DEL ADCON1
		MOVLW 0X00		;CARGA A W UN 00
		MOVWF TRISA		;TRISA = 00000000
		
		BSF TRISE, 0X00
		BSF TRISE, 0X01
		BSF TRISE, 0X02		;PUERTOS DEL PORT E COMO ENTRADA

		BSF TRISD, 0X00
		BSF TRISD, 0X01
		BSF TRISD, 0X02
		BSF TRISD, 0X03
		BSF TRISD, 0X04
		BSF TRISD, 0X05
		BSF TRISD, 0X06
		BSF TRISD, 0X07
				

		BCF STATUS, 5		;BIT 5 DE STATUTAS = 0, BANCO 00
		CALL INICIA_LCD		;LLAMADO A SUBRUTINA
		MOVLW 0X80			;CARGA UN 80 A W
		CALL COMANDO		;LLAMADO A SUBRUTINA

SWITCH_3 	MOVLW 0X00
			MOVWF CENT
			MOVWF DECE 
			MOVWF UNI

			MOVF TRISE, 0X00
			SUBLW 0X00
			BTFSC STATUS, Z
			GOTO NOMBRES
 			;GOTO SEGUNDO_NOMBRE
			GOTO DHB
			


DHB	MOVF TRISE, 0X00
	SUBLW 0X01
	BTFSC STATUS, Z
	GOTO SWITCH8_DEC
	GOTO HEX_BIN


HEX_BIN	MOVF TRISE, 0X00
		SUBLW 0X02
		BTFSC STATUS, Z
		GOTO SWITCH8_HEX
		GOTO BIN


BIN	MOVF TRISE, 0X00
	SUBLW 0X03
	BTFSC STATUS, Z
	GOTO SWITCH8_BIN
	GOTO CARACTER


CARACTER	MOVF TRISE, 0X00
			SUBLW 0X04
			BTFSC STATUS, Z
			GOTO SWITCH8_CAR
			GOTO SWITCH_3


NOMBRES MOVLW a'A'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'T'
		CALL DATOS
		MOVLW a'H'
		CALL DATOS
		MOVLW a' '
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'M'
		CALL DATOS
		MOVLW a'I'
		CALL DATOS
		MOVLW a'L'
		CALL DATOS
		MOVLW a'I'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'N'
		CALL DATOS
		MOVLW a'O'
		CALL DATOS
		
		BCF PORTA, 0
		MOVLW 0XC0
		CALL COMANDO
		
		MOVLW a'G'
		CALL DATOS
		MOVLW a'I'
		CALL DATOS
		MOVLW a'L'
		CALL DATOS
		MOVLW a' '
		CALL DATOS
		MOVLW a'M'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'Q'
		CALL DATOS
		MOVLW a'U'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'Z'
		CALL DATOS


		CALL RET100MS
		CALL RETARDO
		MOVLW H'01'
		CALL COMANDO
		CALL RET100MS
		CALL RET100MS
		CALL RET100MS
		GOTO CAMBIO
		
NOMBRE2
		MOVLW a'C'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'I'
		CALL DATOS
		MOVLW a'S'
		CALL DATOS
		MOVLW a'T'
		CALL DATOS
		MOVLW a'H'
		CALL DATOS
		MOVLW a'I'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'N'
		CALL DATOS
		
		
		BCF PORTA, 0
		MOVLW 0XC0
		CALL COMANDO
		
		MOVLW a'H'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a' '
		CALL DATOS
		MOVLW a'C'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'I'
		CALL DATOS
		MOVLW a'L'
		CALL DATOS
		MOVLW a'L'
		CALL DATOS
		MOVLW a'O'
		CALL DATOS


		CALL RET100MS
		CALL RETARDO
		MOVLW H'01'
		CALL COMANDO
		CALL RET100MS
		CALL RET100MS
		CALL RET100MS
		GOTO CAMBIO2

NOMBRE3

		MOVLW a'A'
		CALL DATOS
		MOVLW a'L'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'J'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'N'
		CALL DATOS
		MOVLW a'D'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'O'
		CALL DATOS

		BCF PORTA, 0
		MOVLW 0XC0
		CALL COMANDO

		MOVLW a'B'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'I'
		CALL DATOS
		MOVLW a'R'
		CALL DATOS
		MOVLW a'O'
		CALL DATOS
		
		MOVLW a' '
		CALL DATOS
		

		MOVLW a'V'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'L'
		CALL DATOS
		MOVLW a'D'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'Z'
		CALL DATOS

		CALL RET100MS
		CALL RETARDO
		MOVLW H'01'
		CALL COMANDO
		CALL RET100MS
		CALL RET100MS
		CALL RET100MS
		GOTO CAMBIO3

NOMBRE4
		MOVLW a'J'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'S'
		CALL DATOS
		MOVLW a'S'
		CALL DATOS
		MOVLW a'I'
		CALL DATOS
		MOVLW a'C'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a' '
		CALL DATOS
		MOVLW a'Z'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'P'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'D'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS

		BCF PORTA, 0
		MOVLW 0XC0
		CALL COMANDO

		MOVLW a'B'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		MOVLW a'E'
		CALL DATOS
		MOVLW a'Z'
		CALL DATOS
		MOVLW a'A'
		CALL DATOS
		
		CALL RET100MS
		CALL RETARDO
		MOVLW H'01'
		CALL COMANDO
		CALL RET100MS
		CALL RET100MS
		CALL RET100MS
	

		GOTO SWITCH_3


CAMBIO MOVF TRISE, 0X00
		SUBLW 0X00
		BTFSS STATUS, Z
		GOTO SWITCH_3
		GOTO NOMBRE2

CAMBIO2 MOVF TRISE, 0X00
		SUBLW 0X00
		BTFSS STATUS, Z
		GOTO SWITCH_3
		GOTO NOMBRE3

CAMBIO3 MOVF TRISE, 0X00
		SUBLW 0X00
		BTFSS STATUS, Z
		GOTO SWITCH_3
		GOTO NOMBRE4

SWITCH8_DEC MOVF TRISD, 0X00
			MOVWF NUM_DECIMAL
			MOVF NUM_DECIMAL, 0X00
			GOTO CENTENAS

CENTENAS MOVLW 0X64
		SUBWF NUM_DECIMAL , 0X01
		BTFSC STATUS, C		;C = 0 NS, C = 0 NS, C = 1 S
		INCF CENT, 0X01		;CENT = 1, = 2, = 2
		BTFSS STATUS, C		;C =0 S, C = 0 S, C = 1 NS
		GOTO CARGARCENTENA	;  -
		GOTO CENTENAS		;-- 
			

CARGARCENTENA MOVF CENT, 0X00
		ADDLW 0X30
		
		CALL DATOS
		MOVLW 0X64
		ADDWF NUM_DECIMAL
		GOTO DECENAS


DECENAS MOVLW 0X0A
		SUBWF NUM_DECIMAL, 0X01
		BTFSC STATUS, C
		INCF DECE, 0X01
		BTFSS STATUS, C
		GOTO CARGARDECENA
		GOTO DECENAS

CARGARDECENA MOVF DECE, 0X00
		ADDLW 0X30
		
		CALL DATOS
		MOVLW 0X0A
		ADDWF NUM_DECIMAL
		GOTO UNIDADES

UNIDADES MOVLW 0X01
		SUBWF NUM_DECIMAL, 0X01
		BTFSC STATUS, C
		INCF UNI, 0X01
		BTFSS STATUS, C
		GOTO CARGARUNIDAD
		GOTO UNIDADES

CARGARUNIDAD MOVF UNI, 0X00
		ADDLW 0X30
		
		CALL DATOS
		CALL RET100MS
		CALL RET100MS
		CALL RET100MS
		MOVLW H'01'
		CALL COMANDO
		CALL RET100MS
		
		GOTO SWITCH_3


			

SWITCH8_HEX BCF STATUS, C
			BCF STATUS, Z
			MOVF TRISD, 0X00
			MOVWF NUM_HEXA
			MOVF NUM_HEXA, 0X00
			ANDLW 0XF0
			MOVWF ALTO_HEXA
			SWAPF ALTO_HEXA, 0X01
			MOVF ALTO_HEXA, 0X00
			SUBLW 0X0A
			BTFSS STATUS, C
			GOTO LETRA_ALTO
			GOTO BAND_Z

BAND_Z BTFSS STATUS, Z
		GOTO NUMERO_ALTO
		GOTO LETRA_ALTO
			
LETRA_ALTO MOVF ALTO_HEXA, 0X00
		ADDLW 0X37
		CALL DATOS
		GOTO BAJO
		

NUMERO_ALTO MOVF ALTO_HEXA, 0X00
		ADDLW 0X30
		CALL DATOS
		GOTO BAJO

BAJO BCF STATUS, C
		BCF STATUS, Z
		MOVF NUM_HEXA, 0X00
		ANDLW 0X0F
		MOVWF BAJO_HEXA
		SUBLW 0X0A
		BTFSS STATUS, C
		GOTO LETRA_BAJO
		GOTO BAND_Z2

BAND_Z2 BTFSS STATUS, Z
		GOTO NUMERO_BAJO
		GOTO LETRA_BAJO

LETRA_BAJO MOVF BAJO_HEXA, 0X00
		ADDLW 0X37
		CALL DATOS
		CALL RET100MS
		CALL RET100MS
		CALL RET100MS
		MOVLW H'01'
		CALL COMANDO
		CALL RET100MS
		GOTO SWITCH_3

NUMERO_BAJO MOVF BAJO_HEXA, 0X00
		ADDLW 0X30
		CALL DATOS
		CALL RET100MS
		CALL RET100MS
		CALL RET100MS
		MOVLW H'01'
		CALL COMANDO
		CALL RET100MS
		GOTO SWITCH_3


SWITCH8_BIN MOVF TRISD, 0X00
			MOVWF NUM_BINARIO
			
			MOVLW 0X08
			MOVWF CONTA_BINARIO
			
	LOOPBIN	RLF NUM_BINARIO
			
			BTFSS STATUS, C
			GOTO ZERO
			GOTO ONE
			

ZERO	MOVLW a'0'
		CALL DATOS
		DECFSZ CONTA_BINARIO
		GOTO LOOPBIN
		CALL RET100MS
		CALL RET100MS
		CALL RET100MS
		MOVLW H'01'
		CALL COMANDO
		CALL RET100MS
		GOTO SWITCH_3


ONE	MOVLW a'1'
	CALL DATOS
	DECFSZ CONTA_BINARIO
	GOTO LOOPBIN
	CALL RET100MS
	CALL RET100MS
	CALL RET100MS
	MOVLW H'01'
	CALL COMANDO
	CALL RET100MS
	GOTO SWITCH_3



SWITCH8_CAR MOVLW 0X40
			CALL COMANDO
						
			MOVLW B'00011100'
			CALL DATOS
			
			MOVLW B'00000101'
			CALL DATOS
			
			MOVLW B'00001111'
			CALL DATOS
			
			MOVLW B'00011111'
			CALL DATOS
			
			MOVLW B'00011110'
			CALL DATOS
			
			MOVLW B'00010100'
			CALL DATOS
			
			MOVLW B'00000111'
			CALL DATOS
			
			MOVLW B'00000000'
			CALL DATOS
			CALL RET100MS

			MOVLW 0X80
			CALL COMANDO
			CALL RET100MS

			MOVLW 0X00
			CALL DATOS
			CALL RET100MS
			CALL RET100MS
			MOVLW H'01'
			CALL COMANDO
			CALL RET100MS

			GOTO CAMBIOA
CARACTER2
			MOVLW 0X47
			CALL COMANDO
			
			
			MOVLW B'00010101'
			CALL DATOS
			
			MOVLW B'00001010'
			CALL DATOS
			
			MOVLW B'00010101'
			CALL DATOS
			
			MOVLW B'00001010'
			CALL DATOS
			
			MOVLW B'00010101'
			CALL DATOS
			
			MOVLW B'00001010'
			CALL DATOS
			
			MOVLW B'00010101'
			CALL DATOS
			
			MOVLW B'00000000'
			CALL DATOS
			CALL RET100MS

			MOVLW 0X81
			CALL COMANDO
			CALL RET100MS

			MOVLW 0X01
			CALL DATOS
			CALL RET100MS
			CALL RET100MS
			MOVLW H'01'
			CALL COMANDO
			CALL RET100MS
		
			GOTO CAMBIOB

CARACTER3
			MOVLW 0X40
			CALL COMANDO
			
			MOVLW B'00001010'
			CALL DATOS
			
			MOVLW B'00000100'
			CALL DATOS
			
			MOVLW B'00001010'
			CALL DATOS
			
			MOVLW B'00011111'
			CALL DATOS
			
			MOVLW B'00010101'
			CALL DATOS
			
			MOVLW B'00001010'
			CALL DATOS
			
			MOVLW B'00010101'
			CALL DATOS
			CALL RET100MS
		
			MOVLW B'00000000'
			CALL DATOS

			MOVLW 0X80
			CALL COMANDO
			CALL RET100MS

			MOVLW 0X00
			CALL DATOS
			CALL RET100MS
			CALL RET100MS
			MOVLW H'01'
			CALL COMANDO
			CALL RET100MS

			GOTO CAMBIOC

CARACTER4
			MOVLW 0X48
			CALL COMANDO
			
			MOVLW B'00011100'
			CALL DATOS
			
			MOVLW B'00001000'
			CALL DATOS
			
			MOVLW B'00011111'
			CALL DATOS
			
			MOVLW B'00010101'
			CALL DATOS
			
			MOVLW B'00011111'
			CALL DATOS
			
			MOVLW B'00000010'
			CALL DATOS
			
			MOVLW B'00000111'
			CALL DATOS
			
			MOVLW B'00000000'
			CALL DATOS
			CALL RET100MS

			MOVLW 0X81
			CALL COMANDO
			CALL RET100MS

			MOVLW 0X01
			CALL DATOS
			CALL RET100MS
			CALL RET100MS
			MOVLW H'01'
			CALL COMANDO
			CALL RET100MS
						


			GOTO SWITCH_3
		
CAMBIOA MOVF TRISE, 0X00
		SUBLW 0X04
		BTFSS STATUS, Z
		GOTO SWITCH_3
		GOTO CARACTER2

CAMBIOB MOVF TRISE, 0X00
		SUBLW 0X04
		BTFSS STATUS, Z
		GOTO SWITCH_3
		GOTO CARACTER3

CAMBIOC MOVF TRISE, 0X00
		SUBLW 0X04
		BTFSS STATUS, Z
		GOTO SWITCH_3
		GOTO CARACTER4


;Comfiguracion del LCD
INICIA_LCD: MOVLW 0X30
			CALL COMANDO
			CALL RET100MS
			MOVLW 0X30
			CALL COMANDO
			CALL RET100MS
			MOVLW 0X38
			CALL COMANDO
			MOVLW 0X0C
			CALL COMANDO
			MOVLW 0X01
			CALL COMANDO
			MOVLW 0X06
			CALL COMANDO
			MOVLW 0X02
			CALL COMANDO
			RETURN

COMANDO: MOVWF PORTB		;PORTB = W
		CALL RET200			;LLAMADO A UN RETARDO
		BCF PORTA, 0		;BIT 0 DEL PORTA = 0  --> RS
		BSF PORTA, 1		;BIT 1 DEL PORTA = 1  --> E
		CALL RET200			;LLAMADO A UN RETARDO
		BCF PORTA, 1		;BIT 1 DEL PORTA = 0  --> E
		RETURN

DATOS: MOVWF PORTB			;PORTB = W
		CALL RET200			;LLAMADO A RETARDO
		BSF PORTA, 0		;BIT 0 DEL PORTA = 1  --> RS
		BSF PORTA, 1		;BIT 1 DEL PORTA = 1  --> E
		CALL RET200			;LLAMADO A RETARDO
		BCF PORTA, 1		;BIT 1 DEL PORTA = 0  --> E
		CALL RET200			;LLAMADO A RETARDO
		CALL RET200			;LLAMADO A RETARDO
		RETURN

RET200 MOVLW 0X02
		MOVWF VALOR1
		LOOP MOVLW d'164'
			MOVWF VALOR
		LOOP1 DECFSZ VALOR, 1
			GOTO LOOP1
		DECFSZ VALOR1, 1
		GOTO LOOP
		RETURN

RET100MS: MOVLW 0X03
		MOVWF VALOR
		TRES: MOVLW 0XFF
			MOVWF VALOR1
		DOS: MOVLW 0XFF
			MOVWF VALOR2
		UNO: DECFSZ VALOR2
			GOTO UNO
		DECFSZ VALOR1
		GOTO DOS
		DECFSZ VALOR
		GOTO TRES
		RETURN



RETARDO MOVLW 0XFF		;Carga una literal a w
		MOVWF 0X33		;Carga el valor de w a 0x22
LOOPRET	CALL RETARDO2	;Llamado a otra subrutina
		DECFSZ 0X33		;Decrementa el valor de la direccion 0x22 y salta si es 0
		GOTO LOOPRET	;Ciclo 
		RETURN			;Retorna a la siguiente linea donde se quedo
RETARDO2 MOVLW 0XFF		;Carga una literal a w
		MOVWF 0X34		;Carga el valor de w a 0x23
LOOP2	CALL RETARDO3	;Llamado a otra subrutina
		DECFSZ 0X34		;Decrementa el valor de la direccion 0x23 y salta si es 0
		GOTO LOOP2		;Ciclo
		RETURN			;Retorna a la siguiente linea donde se quedo
RETARDO3 MOVLW 0X1E		;Carga una literal a w
		MOVWF 0X35		;Carga el valor de w a 0x24
LOOP3	DECFSZ 0X35		;Decrementa el valor de la direccion 0x24 y salta si es 0
		GOTO LOOP3		;Ciclo
		RETURN	


END		;Fin del programa